on: [ push ]
name: Deploy Bicep template
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Getting started
        run: |
          echo Hello from GitHub Actions
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.RG_NAME }}
          template: ./main.bicep
          failOnStdErr: false