on: [ push ]
name: Deploy Bicep template
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Getting started
        run: |
          echo Hello from GitHub Actions
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az account list
#            az account set --subscription 97764cf6-4deb-4911-860a-e78e0ee331b2
#            az group create --name ${{ secrets.RG_NAME }} --location ${{ secrets.LOCATION }}
#            az deployment group what-if --name BicepDeployment --resource-group ${{ secrets.RG_NAME }} --template-file main.bicep